# Generated by Django 3.2.9 on 2021-12-01 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addition', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Extras',
            },
        ),
        migrations.CreateModel(
            name='Pastas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Pastas',
            },
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.DecimalField(decimal_places=2, max_digits=5)),
                ('large', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'RegularPizza',
            },
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Salads',
            },
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.DecimalField(decimal_places=2, max_digits=5)),
                ('large', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'SicilianPizza',
            },
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=30)),
                ('small', models.DecimalField(decimal_places=2, max_digits=5)),
                ('large', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extras', models.ManyToManyField(blank=True, related_name='subs', to='orders.Extras')),
            ],
            options={
                'verbose_name_plural': 'Subs',
            },
        ),
        migrations.DeleteModel(
            name='Pizzas',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dinnerplatters',
            options={'verbose_name_plural': 'DinnerPlatters'},
        ),
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'Toppings'},
        ),
        migrations.RenameField(
            model_name='dinnerplatters',
            old_name='name',
            new_name='dinner',
        ),
        migrations.AddField(
            model_name='dinnerplatters',
            name='large',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinnerplatters',
            name='small',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sicilianPrice', to='orders.category'),
        ),
        migrations.AddField(
            model_name='regularpizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularPrice', to='orders.category'),
        ),
    ]
