# Generated by Django 3.2.9 on 2021-12-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211214_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs',
            name='extras',
        ),
    ]
