# Generated by Django 3.2.9 on 2021-12-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='toppings',
            field=models.ManyToManyField(to='orders.Toppings'),
        ),
        migrations.AddField(
            model_name='regularpizza',
            name='max_toppings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='max_toppings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subs',
            name='max_toppings',
            field=models.IntegerField(default=3),
        ),
    ]
